# Extracts the skeleton and the Walk / Idle motion-capture clips from three.js's Soldier.glb
# (a Mixamo rig) into src/scene/data/climberRig.ts. Only bones and animation keys are kept;
# the soldier's mesh and textures are not used.
#   curl -o /tmp/Soldier.glb https://raw.githubusercontent.com/mrdoob/three.js/r180/examples/models/gltf/Soldier.glb
#   python3 tools/character/extract.py /tmp/Soldier.glb src/scene/data/climberRig.ts
import json, struct, sys
import numpy as np

src, out = sys.argv[1], sys.argv[2]
b = open(src, "rb").read()
jl = struct.unpack("<I", b[12:16])[0]
j = json.loads(b[20:20 + jl])
bin0 = 20 + jl + 8

def accessor(i):
    a = j["accessors"][i]
    bv = j["bufferViews"][a["bufferView"]]
    n = {"SCALAR": 1, "VEC3": 3, "VEC4": 4}[a["type"]]
    off = bin0 + bv.get("byteOffset", 0) + a.get("byteOffset", 0)
    return np.frombuffer(b, dtype="<f4", count=a["count"] * n, offset=off).reshape(a["count"], n)

nodes = j["nodes"]
parent = {}
for i, n in enumerate(nodes):
    for c in n.get("children", []):
        parent[c] = i

def keep(name):
    return name.startswith("mixamorig:") and not any(f in name for f in ("Thumb", "Index", "Ring", "Pinky")) \
        and not ("Middle" in name and not name.endswith("Middle1"))

kept = [i for i, n in enumerate(nodes) if keep(n["name"])]
index = {i: k for k, i in enumerate(kept)}
r4 = lambda v: [round(float(x), 4) for x in v]
bones = []
for i in kept:
    n = nodes[i]
    bones.append({
        "name": n["name"].replace("mixamorig:", ""),
        "parent": index.get(parent.get(i, -1), -1),
        "t": r4(n.get("translation", [0, 0, 0])),
        "r": r4(n.get("rotation", [0, 0, 0, 1])),
    })

clips = {}
for a in j["animations"]:
    if a["name"] not in ("Walk", "Idle"):
        continue
    tracks = []
    duration = 0
    for ch in a["channels"]:
        node = ch["target"]["node"]
        path = ch["target"]["path"]
        if node not in index or path == "scale":
            continue
        name = nodes[node]["name"].replace("mixamorig:", "")
        if path == "translation" and name != "Hips":
            continue
        s = a["samplers"][ch["sampler"]]
        times = accessor(s["input"])[:, 0]
        vals = accessor(s["output"])
        if path == "translation":
            vals = vals.copy()
            vals[:, 0] = vals[0, 0]  # keep the walk in place: no sideways or forward drift
        if path == "rotation" and np.allclose(vals, vals[0], atol=1e-4):
            continue
        duration = max(duration, float(times[-1]))
        tracks.append({
            "bone": name,
            "path": "quaternion" if path == "rotation" else "position",
            "times": [round(float(t), 4) for t in times],
            "values": [round(float(v), 4) for v in vals.reshape(-1)],
        })
    clips[a["name"]] = {"duration": round(duration, 4), "tracks": tracks}

root = nodes[0]
with open(out, "w") as f:
    f.write("// GENERATED by tools/character/extract.py. Skeleton and Walk / Idle motion capture from\n")
    f.write("// three.js's Soldier.glb (Adobe Mixamo rig, distributed with three.js examples). No mesh or textures.\n\n")
    f.write("export interface RigBone { name: string; parent: number; t: number[]; r: number[] }\n")
    f.write("export interface RigTrack { bone: string; path: 'quaternion' | 'position'; times: number[]; values: number[] }\n\n")
    f.write(f"/** Root transform: centimeters to meters, Z-up to Y-up. */\nexport const RIG_ROOT = {{ r: {r4(root['rotation'])}, s: {root['scale'][0]} }};\n\n")
    f.write("export const RIG_BONES: RigBone[] = " + json.dumps(bones) + ";\n\n")
    f.write("export const RIG_CLIPS: Record<'Walk' | 'Idle', { duration: number; tracks: RigTrack[] }> = " + json.dumps(clips) + ";\n")
print("bones", len(bones), {k: (v["duration"], len(v["tracks"])) for k, v in clips.items()})
