/// <reference types="node" />
// Writes src/game/data/routeProfile.ts: for every route, distance along the route and real
// elevation at every route point, plus where each stop sits. The game rules use this; the 3D scene
// uses the same points (src/scene/terrain.ts buildRoute), so a distance means the same place in both.
//   npx tsx tools/route/profile.ts
import { writeFileSync } from 'node:fs';
import { ROUTE_IDS } from '../../src/game/routes';
import { buildRoute } from '../../src/scene/terrain';

const r1 = (v: number) => Math.round(v * 10) / 10;
let out = `// GENERATED by tools/route/profile.ts from the real terrain. Do not edit by hand.
export interface RouteProfile {
  /** Meters along the route from the trailhead, one entry per route point. */
  dist: number[];
  /** Elevation (m) at each route point. */
  elev: number[];
  /** Distance (m) of each stop in the route's nodes. */
  nodeDist: number[];
}

export const PROFILES: Record<string, RouteProfile> = {
`;
for (const id of ROUTE_IDS) {
  const r = buildRoute(id);
  const nodeDist = r.nodeIndex.map((i) => r1(r.cum[i]));
  out += `  ${id}: {\n    dist: ${JSON.stringify(r.cum.map(r1))},\n    elev: ${JSON.stringify(r.pts.map((p) => r1(p[1])))},\n    nodeDist: ${JSON.stringify(nodeDist)},\n  },\n`;
  console.log(id.padEnd(8), 'points', r.pts.length, 'total m', Math.round(r.cum[r.cum.length - 1]), 'nodes', nodeDist.join(', '));
}
out += '};\n';
writeFileSync('src/game/data/routeProfile.ts', out);
