/// <reference types="node" />
// Writes src/game/data/routeProfile.ts: distance along the route and real elevation at every
// route point, plus where each stop sits. The game rules use this; the 3D scene uses the same
// points (src/scene/terrain.ts ROUTE), so a distance means the same place in both.
//   npx tsx tools/route/profile.ts
import { writeFileSync } from 'node:fs';
import { ROUTE } from '../../src/scene/terrain';

const dist: number[] = [0];
for (let i = 1; i < ROUTE.pts.length; i++) {
  const [ax, , az] = ROUTE.pts[i - 1];
  const [bx, , bz] = ROUTE.pts[i];
  dist.push(dist[i - 1] + Math.hypot(bx - ax, bz - az));
}
const elev = ROUTE.pts.map((p) => Math.round(p[1] * 10) / 10);
const nodeDist = ROUTE.nodeIndex.map((i) => Math.round(dist[i] * 10) / 10);
const out = `// GENERATED by tools/route/profile.ts from the real terrain. Do not edit by hand.
/** Meters along the route from Paradise, one entry per route point. */
export const PROFILE_DIST: number[] = ${JSON.stringify(dist.map((d) => Math.round(d * 10) / 10))};
/** Elevation (m) at each route point. */
export const PROFILE_ELEV: number[] = ${JSON.stringify(elev)};
/** Distance (m) of each stop in NODES. */
export const NODE_DIST: number[] = ${JSON.stringify(nodeDist)};
`;
writeFileSync('src/game/data/routeProfile.ts', out);
console.log('points', dist.length, 'total m', Math.round(dist[dist.length - 1]), 'nodes', nodeDist.join(', '));
