// GENERATED by tools/route/waypoints.ts. Do not edit by hand. Positions approximate; see the tool.
export const ROUTE_WAYPOINTS: Record<'emmons' | 'kautz' | 'liberty', { name: string; x: number; z: number; dem: number }[]> = {
 "emmons": [
  {
   "name": "White River",
   "x": 8084.8,
   "z": -8707.3,
   "dem": 1340.9
  },
  {
   "name": "Glacier Basin",
   "x": 5076.5,
   "z": -7198.8,
   "dem": 1798.7
  },
  {
   "name": "Inter Glacier",
   "x": 3922.7,
   "z": -6734.9,
   "dem": 1916.3
  },
  {
   "name": "Camp Curtis",
   "x": 2574.8,
   "z": -5731.3,
   "dem": 2639.5
  },
  {
   "name": "Camp Schurman",
   "x": 1600.8,
   "z": -4622.4,
   "dem": 2883.3
  },
  {
   "name": "Emmons Flats",
   "x": 1445.7,
   "z": -4418.5,
   "dem": 3005
  },
  {
   "name": "Top of the Corridor",
   "x": 714,
   "z": -3968.8,
   "dem": 3449.8
  },
  {
   "name": "Upper Emmons",
   "x": 68.5,
   "z": -3619.2,
   "dem": 3901.3
  },
  {
   "name": "Crater Rim",
   "x": -488.9,
   "z": -3208.3,
   "dem": 4328.3
  },
  {
   "name": "Columbia Crest",
   "x": -802.2,
   "z": -3095.8,
   "dem": 4391.5
  }
 ],
 "kautz": [
  {
   "name": "Paradise",
   "x": 1149.7,
   "z": 4405.8,
   "dem": 1646
  },
  {
   "name": "Glacier Vista",
   "x": 1102.1,
   "z": 2750,
   "dem": 1909.5
  },
  {
   "name": "Nisqually Glacier",
   "x": 218.5,
   "z": 2266.4,
   "dem": 1858.4
  },
  {
   "name": "Wilson Glacier",
   "x": -587,
   "z": 1163.2,
   "dem": 2316.1
  },
  {
   "name": "Wapowety Cleaver",
   "x": -721.7,
   "z": -142.6,
   "dem": 2895.8
  },
  {
   "name": "Camp Hazard",
   "x": -1142.1,
   "z": -1277.2,
   "dem": 3444.1
  },
  {
   "name": "Top of the Ice Chute",
   "x": -1284.4,
   "z": -1723.8,
   "dem": 3749.3
  },
  {
   "name": "Crater Rim",
   "x": -643.6,
   "z": -2748.7,
   "dem": 4312.9
  },
  {
   "name": "Columbia Crest",
   "x": -802.2,
   "z": -3095.8,
   "dem": 4391.5
  }
 ],
 "liberty": [
  {
   "name": "White River",
   "x": 8084.8,
   "z": -8707.3,
   "dem": 1340.9
  },
  {
   "name": "Glacier Basin",
   "x": 5076.5,
   "z": -7198.8,
   "dem": 1798.7
  },
  {
   "name": "St. Elmo Pass",
   "x": 3039.9,
   "z": -8246.7,
   "dem": 2255.4
  },
  {
   "name": "Winthrop Glacier",
   "x": 1904.2,
   "z": -7792.4,
   "dem": 1996.8
  },
  {
   "name": "Curtis Ridge",
   "x": 152.3,
   "z": -7903.7,
   "dem": 2236.8
  },
  {
   "name": "Base of Liberty Ridge",
   "x": -1242.5,
   "z": -6924.5,
   "dem": 2438
  },
  {
   "name": "Thumb Rock",
   "x": -1655.7,
   "z": -5433,
   "dem": 3279.7
  },
  {
   "name": "Black Pyramid",
   "x": -1778,
   "z": -4979.4,
   "dem": 3657.5
  },
  {
   "name": "Liberty Cap",
   "x": -1893,
   "z": -4241.1,
   "dem": 4295.3
  },
  {
   "name": "Columbia Crest",
   "x": -802.2,
   "z": -3095.8,
   "dem": 4391.5
  }
 ]
};
