# Writes src/scene/data/rainierDem.ts from the grids made by process.py and route.py.
# Heights are stored as uint16 decimeters, base64-encoded.
import base64, json, sys
import numpy as np

D, OUT = sys.argv[1], sys.argv[2]
core = np.load(f"{D}/core.npy")
far = np.load(f"{D}/far.npy")
route = json.load(open(f"{D}/route.json"))

def enc(a):
    return base64.b64encode(np.clip(np.round(a * 10), 0, 65535).astype("<u2").tobytes()).decode()

with open(OUT, "w") as f:
    f.write("// GENERATED by tools/dem/export.py. Do not edit by hand.\n")
    f.write("// Elevation: AWS Terrain Tiles (Terrarium), derived from USGS 3DEP / SRTM. Public domain / open data.\n")
    f.write("// Local frame: x = meters east, z = meters south of 46.825 N, 121.750 W; heights in meters above sea level.\n\n")
    f.write(f"export const CORE_HALF = 11000;\nexport const CORE_N = {core.shape[0]};\n")
    f.write(f"export const FAR_HALF = 45000;\nexport const FAR_N = {far.shape[0]};\n\n")
    f.write("export const WAYPOINTS: { name: string; x: number; z: number; dem: number }[] = ")
    f.write(json.dumps([{k: p[k] for k in ("name", "x", "z", "dem")} for p in route], indent=2))
    f.write(";\n\n")
    f.write(f"export const CORE_B64 =\n  '{enc(core)}';\n\n")
    f.write(f"export const FAR_B64 =\n  '{enc(far)}';\n")
print("wrote", OUT)
