# Elevation data for the career mountains: Mount St. Helens, Mount Adams, Mount Baker and Mount Si.
# Same source and encoding as Rainier (AWS Terrain Tiles, Terrarium; USGS 3DEP / SRTM, open data).
# Writes src/scene/data/dem_<id>.ts with a detailed CORE, a 90 km FAR ring and a 350 km HORIZON.
#   pip install numpy pillow
#   python3 tools/dem/volcanoes.py /tmp/dem-volcanoes src/scene/data
import base64, math, os, subprocess, sys, time
import numpy as np
from PIL import Image

CACHE, OUT = sys.argv[1], sys.argv[2]
os.makedirs(CACHE, exist_ok=True)

# id: (center lat, lon, core half-size m, core grid n). Centers sit between trailhead and summit.
MOUNTAINS = {
    "helens": (46.172, -122.190, 6000, 401),
    "adams": (46.168, -121.494, 7000, 401),
    "baker": (48.742, -121.815, 7000, 401),
    "si": (47.489, -121.730, 4000, 321),
}
M_LAT = 111320.0

def tile_xy(lat, lon, z):
    n = 2 ** z
    return (lon + 180) / 360 * n, (1 - np.arcsinh(np.tan(np.radians(lat))) / np.pi) / 2 * n

def fetch(z, x, y):
    p = f"{CACHE}/{z}_{x}_{y}.png"
    url = f"https://s3.amazonaws.com/elevation-tiles-prod/terrarium/{z}/{x}/{y}.png"
    for attempt in range(6):
        if os.path.exists(p) and open(p, "rb").read(8) == b"\x89PNG\r\n\x1a\n":
            return p
        subprocess.run(["curl", "-sS", "--retry", "3", "-o", p, url], check=False)
        time.sleep(0.5 * attempt)
    raise RuntimeError(f"could not fetch tile {z}/{x}/{y}")

def sampler(lat0, lon0, half, z):
    """Stitches the tiles covering the square and returns a bilinear sampler in lat/lon."""
    dlat = half / M_LAT
    dlon = half / (M_LAT * math.cos(math.radians(lat0)))
    x0, y0 = tile_xy(lat0 + dlat, lon0 - dlon, z)
    x1, y1 = tile_xy(lat0 - dlat, lon0 + dlon, z)
    tx0, ty0, tx1, ty1 = int(x0), int(y0), int(x1), int(y1)
    img = np.zeros(((ty1 - ty0 + 1) * 256, (tx1 - tx0 + 1) * 256), dtype=np.float32)
    for ty in range(ty0, ty1 + 1):
        for tx in range(tx0, tx1 + 1):
            a = np.asarray(Image.open(fetch(z, tx, ty)).convert("RGB"), dtype=np.float32)
            img[(ty - ty0) * 256:(ty - ty0 + 1) * 256, (tx - tx0) * 256:(tx - tx0 + 1) * 256] = a[..., 0] * 256 + a[..., 1] + a[..., 2] / 256 - 32768

    def sample(lat, lon):
        x, y = tile_xy(lat, lon, z)
        px = (x - tx0) * 256 - 0.5
        py = (y - ty0) * 256 - 0.5
        xi = np.clip(np.floor(px).astype(int), 0, img.shape[1] - 2)
        yi = np.clip(np.floor(py).astype(int), 0, img.shape[0] - 2)
        fx = np.clip(px - xi, 0, 1); fy = np.clip(py - yi, 0, 1)
        return (img[yi, xi] * (1 - fx) * (1 - fy) + img[yi, xi + 1] * fx * (1 - fy)
                + img[yi + 1, xi] * (1 - fx) * fy + img[yi + 1, xi + 1] * fx * fy)
    return sample

def grid(lat0, lon0, half, n, z):
    s = sampler(lat0, lon0, half, z)
    xs = np.linspace(-half, half, n)
    X, Z = np.meshgrid(xs, xs)  # rows = z (north to south), cols = x (west to east)
    lat = lat0 - Z / M_LAT
    lon = lon0 + X / (M_LAT * math.cos(math.radians(lat0)))
    return s(lat, lon).astype(np.float32)

def enc(a):
    return base64.b64encode(np.clip(np.round(np.maximum(a, 0) * 10), 0, 65535).astype("<u2").tobytes()).decode()

for mid, (lat0, lon0, half, n) in MOUNTAINS.items():
    core = grid(lat0, lon0, half, n, 13)
    far = grid(lat0, lon0, 45000, 193, 10)
    horizon = grid(lat0, lon0, 175000, 257, 8)
    path = f"{OUT}/dem_{mid}.ts"
    with open(path, "w") as f:
        f.write("// GENERATED by tools/dem/volcanoes.py. Do not edit by hand.\n")
        f.write("// Elevation: AWS Terrain Tiles (Terrarium), derived from USGS 3DEP / SRTM. Public domain / open data.\n")
        f.write(f"// Local frame: x = meters east, z = meters south of {lat0} N, {-lon0} W; heights in meters.\n\n")
        f.write(f"export const LAT0 = {lat0};\nexport const LON0 = {lon0};\n")
        f.write(f"export const CORE_HALF = {half};\nexport const CORE_N = {n};\n")
        f.write(f"export const FAR_HALF = 45000;\nexport const FAR_N = 193;\n")
        f.write(f"export const HORIZON_HALF = 175000;\nexport const HORIZON_N = 257;\n\n")
        f.write(f"export const CORE_B64 =\n  '{enc(core)}';\n\nexport const FAR_B64 =\n  '{enc(far)}';\n\nexport const HORIZON_B64 =\n  '{enc(horizon)}';\n")
    print(f"{mid:7s} core {core.min():6.0f}..{core.max():6.0f} m  far max {far.max():6.0f}  -> {path} ({os.path.getsize(path) // 1024} KB)")
